import 'dart:async';

import 'package:academyhub_mobile/config/api_config.dart';
import 'package:academyhub_mobile/config/app_theme.dart';
import 'package:academyhub_mobile/main.dart' as NavigationService;
import 'package:academyhub_mobile/providers/absence_justification_provider.dart';
import 'package:academyhub_mobile/providers/academic_calendar_provider.dart';
import 'package:academyhub_mobile/providers/assessment_provider.dart';
import 'package:academyhub_mobile/providers/attendance_provider.dart';
import 'package:academyhub_mobile/providers/auth_provider.dart';
import 'package:academyhub_mobile/providers/offline_sync_provider.dart';
import 'package:academyhub_mobile/providers/class_provider.dart';
import 'package:academyhub_mobile/providers/dashboard_provider.dart';
import 'package:academyhub_mobile/providers/enrollment_provider.dart';
import 'package:academyhub_mobile/providers/expense_provider.dart';
import 'package:academyhub_mobile/providers/financial_automation_provider.dart';
import 'package:academyhub_mobile/providers/app_notification_provider.dart';
import 'package:academyhub_mobile/providers/guardian_official_documents_provider.dart';
import 'package:academyhub_mobile/providers/horario_provider.dart';
import 'package:academyhub_mobile/providers/invoice_provider.dart';
import 'package:academyhub_mobile/providers/report_card_provider.dart';
import 'package:academyhub_mobile/providers/re_enrollment_provider.dart';

import 'package:academyhub_mobile/providers/schedule_provider.dart';
import 'package:academyhub_mobile/providers/school_provider.dart';
import 'package:academyhub_mobile/providers/student_note_provider.dart';
import 'package:academyhub_mobile/providers/student_provider.dart';
import 'package:academyhub_mobile/providers/subject_provider.dart';
import 'package:academyhub_mobile/providers/theme_provider.dart';
import 'package:academyhub_mobile/providers/user_provider.dart';
import 'package:academyhub_mobile/providers/whatsapp_provider.dart';
import 'package:academyhub_mobile/screens/negotiation.data.dart';
import 'package:academyhub_mobile/screens/public_registration_screen.dart';
import 'package:academyhub_mobile/screens/student/student_invoices_screen.dart';
import 'package:academyhub_mobile/services/report_card_service.dart';
import 'package:academyhub_mobile/services/websocket.dart';
import 'package:academyhub_mobile/student_access/student_exam_execution_screen.dart';
import 'package:academyhub_mobile/student_access/student_exam_login_screen.dart';
import 'package:academyhub_mobile/student_access/student_exam_result_screen.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:academyhub_mobile/dashboard.dart';
import 'package:academyhub_mobile/screens/loginPage.dart';
import 'package:academyhub_mobile/screens/guardian_home_placeholder_screen.dart';
import 'package:academyhub_mobile/screens/splash_screen.dart';
import 'package:academyhub_mobile/services/notification.service.dart';
import 'package:academyhub_mobile/widgets/app_update_banner.dart';
import 'package:academyhub_mobile/widgets/app_update_diagnostics_screen.dart';
import 'package:academyhub_mobile/widgets/offline_sync_banner.dart';
import 'package:flutter_web_plugins/url_strategy.dart';

// import 'firebase_options.dart'; // Ensure this file is generated by running `flutterfire configure`

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
    GlobalKey<ScaffoldMessengerState>();

void main() {
  // The first frame must never depend on a platform SDK. A stalled Firebase
  // initialization used to prevent runApp from being called, leaving iOS on a
  // completely white screen with no recovery UI.
  WidgetsFlutterBinding.ensureInitialized();

  // Path URL handling is a web concern. Calling it on a native launcher is
  // unnecessary and makes startup less predictable across platform versions.
  if (kIsWeb) {
    usePathUrlStrategy();
  }

  // Render the application before optional platform services. If locale data
  // or Firebase is unavailable, login remains usable and the failure is
  // observable in debug logs rather than becoming an infinite white screen.
  runZonedGuarded(
    () {
      runApp(
        MultiProvider(
          providers: [
            ChangeNotifierProvider(
              create: (_) => ReportCardProvider(
                service: ReportCardService(baseUrl: ApiConfig.baseUrl),
              ),
            ),
            ChangeNotifierProvider(create: (_) => ThemeProvider()),
            ChangeNotifierProvider(create: (_) => EnrollmentProvider()),
            ChangeNotifierProvider(create: (_) => StudentNoteProvider()),
            ChangeNotifierProvider(
              create: (_) => AbsenceJustificationProvider(),
            ),
            ChangeNotifierProvider(create: (_) => HorarioProvider()),
            ChangeNotifierProvider(create: (_) => ExpenseProvider()),
            ChangeNotifierProvider(create: (_) => AttendanceProvider()),
            ChangeNotifierProvider(create: (_) => AuthProvider()),
            ChangeNotifierProxyProvider<AuthProvider, OfflineSyncProvider>(
              create: (_) => OfflineSyncProvider(),
              update: (_, auth, previous) {
                final sync = previous ?? OfflineSyncProvider();
                unawaited(sync.updateAuth(auth));
                return sync;
              },
            ),
            ChangeNotifierProvider(create: (_) => AppNotificationProvider()),
            ChangeNotifierProvider(create: (_) => StudentProvider()),
            ChangeNotifierProvider(create: (_) => UserProvider()),
            ChangeNotifierProvider(create: (_) => NegotiationProvider()),
            ChangeNotifierProvider(create: (_) => InvoiceProvider()),
            ChangeNotifierProvider(create: (_) => ReEnrollmentProvider()),
            ChangeNotifierProvider(
              create: (_) => GuardianOfficialDocumentsProvider(),
            ),
            ChangeNotifierProvider(create: (_) => SubjectProvider()),
            ChangeNotifierProvider(create: (_) => ClassProvider()),
            ChangeNotifierProvider(create: (_) => WhatsappProvider()),
            ChangeNotifierProvider(create: (_) => AssessmentProvider()),
            ChangeNotifierProvider(create: (_) => DashboardProvider()),
            ChangeNotifierProvider(create: (_) => SchoolProvider()),

            // 👉 ADICIONE ESTA LINHA AQUI:
            Provider<WebSocketService>(create: (_) => WebSocketService()),

            // ==============================================================
            // [CORREÇÃO APLICADA] Uso do "previous ??" para evitar descarte
            // ==============================================================
            ChangeNotifierProxyProvider<AuthProvider, AcademicCalendarProvider>(
              create: (context) => AcademicCalendarProvider(
                Provider.of<AuthProvider>(context, listen: false),
              ),
              update: (context, auth, previous) =>
                  previous ?? AcademicCalendarProvider(auth),
            ),
            ChangeNotifierProxyProvider<AuthProvider, ScheduleProvider>(
              create: (context) => ScheduleProvider(
                Provider.of<AuthProvider>(context, listen: false),
              ),
              update: (context, auth, previous) =>
                  previous ?? ScheduleProvider(auth),
            ),
          ],
          child: const MyApp(),
        ),
      );
      // NotificationService only receives global keys. Initializing it after
      // runApp keeps every native/plugin-adjacent call inside the guarded
      // startup path and guarantees the first Flutter frame is scheduled.
      NotificationService.instance.init(scaffoldMessengerKey);
    },
    (error, stack) {
      runApp(ErrorApp(error: error.toString(), stack: stack.toString()));
    },
  );

  unawaited(_initializeOptionalPlatformServices());
}

Future<void> _initializeOptionalPlatformServices() async {
  try {
    await initializeDateFormatting(
      'pt_BR',
      null,
    ).timeout(const Duration(seconds: 8));
  } on TimeoutException {
    debugPrint('⚠️ [Main] Locale data initialization timed out.');
  } catch (error) {
    debugPrint('⚠️ [Main] Locale data initialization failed: $error');
  }

  if (kIsWeb) {
    debugPrint('🌐 [Main] Firebase/notifications are disabled on the web.');
    return;
  }

  try {
    await Firebase.initializeApp().timeout(const Duration(seconds: 10));
    debugPrint('🔥 [Main] Firebase initialized.');
  } on TimeoutException {
    debugPrint('⚠️ [Main] Firebase initialization timed out.');
  } catch (error) {
    debugPrint('⚠️ [Main] Firebase initialization failed: $error');
  }
}

// ... ErrorApp
class ErrorApp extends StatelessWidget {
  final String error;
  final String stack;

  const ErrorApp({super.key, required this.error, required this.stack});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: NavigationService.navigatorKey,
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: const Color(0xFFB71C1C),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Icon(
                    Icons.error_outline,
                    color: Colors.white,
                    size: 60,
                  ),
                  const SizedBox(height: 20),
                  const Text(
                    "ERRO NA INICIALIZAÇÃO",
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 24,
                    ),
                  ),
                  const SizedBox(height: 10),
                  const Text(
                    "O aplicativo encontrou um erro fatal antes de iniciar.",
                    style: TextStyle(color: Colors.white70, fontSize: 16),
                  ),
                  const SizedBox(height: 30),
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: Colors.black26,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Colors.yellowAccent),
                    ),
                    child: SelectableText(
                      error,
                      style: const TextStyle(
                        color: Colors.yellowAccent,
                        fontFamily: 'Courier',
                        fontWeight: FontWeight.bold,
                        fontSize: 14,
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  const Text(
                    "Detalhes Técnicos:",
                    style: TextStyle(color: Colors.white70),
                  ),
                  const Divider(color: Colors.white30),
                  SelectableText(
                    stack,
                    style: const TextStyle(
                      color: Colors.white60,
                      fontFamily: 'Courier',
                      fontSize: 10,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static final GoRouter _router = GoRouter(
    navigatorKey: navigatorKey,
    initialLocation: '/',
    errorBuilder: (context, state) => Scaffold(
      body: Center(child: Text('Página não encontrada: ${state.error}')),
    ),
    routes: [
      GoRoute(
        path: '/support/update-diagnostics',
        builder: (context, state) => const AppUpdateDiagnosticsScreen(),
      ),
      GoRoute(
        path: '/matricula-web/:schoolId',
        builder: (context, state) {
          final schoolId = state.pathParameters['schoolId'];
          final onlyMinors =
              state.uri.queryParameters['onlyMinors']?.toLowerCase() == 'true';
          return PublicRegistrationScreen(
            schoolId: schoolId!,
            onlyMinors: onlyMinors,
          );
        },
      ),
      GoRoute(
        path: '/pagar/:token',
        builder: (context, state) {
          final token = state.pathParameters['token']!;
          return NegotiationPaymentScreen(negotiationToken: token);
        },
      ),

      // =========================================================
      // 🌟 ROTA PARA A TELA DE MENSALIDADES (DESTINO DO MAGIC LINK)
      // =========================================================
      GoRoute(
        path: '/aluno/faturas',
        builder: (context, state) => const StudentInvoicesScreen(),
      ),

      // =========================================================
      // 🌟 NOVA ROTA: CAPTURA DO MAGIC LINK
      // =========================================================
      GoRoute(
        path: '/auth/student/access-by-token',
        builder: (context, state) {
          final token = state.uri.queryParameters['token'];

          if (token == null || token.isEmpty) {
            return const Scaffold(
              body: Center(
                child: Text('Token de acesso não fornecido ou inválido.'),
              ),
            );
          }

          return StudentTokenHandlerScreen(token: token);
        },
      ),
      // =========================================================

      GoRoute(
        path: '/aluno/prova/:assessmentId',
        builder: (context, state) {
          final assessmentId = state.pathParameters['assessmentId'];
          if (assessmentId == null) {
            return const Scaffold(body: Center(child: Text("ID inválido")));
          }
          return StudentExamLoginScreen(assessmentId: assessmentId);
        },
        routes: [
          GoRoute(
            path: 'execucao',
            builder: (context, state) {
              final assessmentId = state.pathParameters['assessmentId']!;
              return StudentExamExecutionScreen(assessmentId: assessmentId);
            },
          ),
          GoRoute(
            path: 'resultado',
            builder: (context, state) {
              final extras = state.extra as Map<String, dynamic>?;
              if (extras == null) {
                return const Scaffold(
                  body: Center(
                    child: Text("Dados do resultado não encontrados."),
                  ),
                );
              }
              return StudentExamResultScreen(
                assessment: extras['assessment'],
                attempt: extras['attempt'],
              );
            },
          ),
        ],
      ),
      GoRoute(
        path: '/',
        builder: (context, state) => AuthWrapper(
          startInGuardianMode: state.uri.queryParameters['mode'] == 'guardian',
        ),
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return LayoutBuilder(
      builder: (context, constraints) {
        final bool isMobile = constraints.maxWidth < 768;
        final Size designSize = isMobile
            ? const Size(390, 844)
            : const Size(1920, 1080);

        return ScreenUtilInit(
          designSize: designSize,
          minTextAdapt: true,
          splitScreenMode: true,
          builder: (context, child) {
            return MaterialApp.router(
              routerConfig: _router,
              scaffoldMessengerKey: scaffoldMessengerKey,
              builder: (context, child) => OfflineSyncBanner(
                child: AppUpdateWatcher(
                  child: child ?? const SizedBox.shrink(),
                ),
              ),
              title: 'Academy Hub',
              debugShowCheckedModeBanner: false,
              theme: AppTheme.lightTheme,
              darkTheme: AppTheme.darkTheme,
              themeMode: themeProvider.themeMode,
              localizationsDelegates: const [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              supportedLocales: const [Locale('pt', 'BR'), Locale('en', 'US')],
              locale: const Locale('pt', 'BR'),
            );
          },
        );
      },
    );
  }
}

class AuthWrapper extends StatelessWidget {
  final bool startInGuardianMode;

  const AuthWrapper({super.key, this.startInGuardianMode = false});

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (ctx, auth, _) {
        if (auth.isAuthenticated) {
          if (auth.isGuardian) {
            return const GuardianHomePlaceholderScreen();
          }
          return const Dashboard();
        }
        return FutureBuilder(
          future: auth.tryAutoLogin(context),
          builder: (ctx, authResultSnapshot) {
            if (authResultSnapshot.connectionState == ConnectionState.waiting) {
              return const SplashScreen();
            }
            return Loginpage(startInGuardianMode: startInGuardianMode);
          },
        );
      },
    );
  }
}

// ====================================================================
// 🌟 TELA DE HANDLER: PROCESSA O MAGIC LINK SILENCIOSAMENTE
// ====================================================================
class StudentTokenHandlerScreen extends StatefulWidget {
  final String token;
  const StudentTokenHandlerScreen({super.key, required this.token});

  @override
  State<StudentTokenHandlerScreen> createState() =>
      _StudentTokenHandlerScreenState();
}

class _StudentTokenHandlerScreenState extends State<StudentTokenHandlerScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _validateAndLogin();
    });
  }

  Future<void> _validateAndLogin() async {
    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);

      // Chamada real para a sua API validando o token temporário
      final bool success = await authProvider.loginWithMagicLink(
        widget.token,
        context,
      );

      if (!mounted) return;

      if (success) {
        // [AJUSTADO] Direciona para a rota da tela de faturas do aluno!
        context.go('/aluno/faturas');
      } else {
        _showErrorAndRedirect(
          "Este link expirou ou é inválido. Solicite um novo acesso no WhatsApp.",
        );
      }
    } catch (e) {
      if (!mounted) return;
      _showErrorAndRedirect(
        "Erro ao tentar acessar. Tente novamente mais tarde.",
      );
    }
  }

  void _showErrorAndRedirect(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red.shade800,
        behavior: SnackBarBehavior.floating,
      ),
    );
    // Manda de volta pra tela de login principal
    context.go('/');
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(color: theme.primaryColor),
            const SizedBox(height: 24),
            Text(
              "Autenticando acesso seguro...",
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w500,
                color: theme.textTheme.bodyLarge?.color,
              ),
            ),
            const SizedBox(height: 8),
            const Text(
              "Você será redirecionado para suas faturas em instantes.",
              style: TextStyle(color: Colors.grey),
            ),
          ],
        ),
      ),
    );
  }
}
